;;; melpa.el --- Build the MELPA recipe locally -*- lexical-binding: t; -*-

(setq user-emacs-directory (expand-file-name ".build/emacs/")
      custom-file (expand-file-name "custom.el" user-emacs-directory))
(require 'package)
(setq package-user-dir (expand-file-name ".build/elpa")
      package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-initialize)
(unless (package-installed-p 'package-build)
  (package-refresh-contents)
  (package-install 'package-build))
(require 'package-build)

(setq package-build-working-dir (expand-file-name ".build/melpa/working/")
      package-build-archive-dir (expand-file-name ".build/melpa/packages/")
      package-build-recipes-dir (expand-file-name ".build/melpa/recipes/")
      package-build-releases (equal (getenv "MELPA_CHANNEL") "stable"))
(make-directory package-build-recipes-dir t)
(let ((recipe (with-temp-buffer
                (insert-file-contents "recipes/markdown-modern")
                (read (current-buffer))))
      (branch (getenv "MELPA_BRANCH")))
  (when (and branch (not (string-empty-p branch)))
    (setcdr recipe (plist-put (cdr recipe) :branch branch)))
  (with-temp-file (expand-file-name "markdown-modern" package-build-recipes-dir)
    (prin1 recipe (current-buffer))
    (insert "\n")))
(package-build-archive "markdown-modern")
